version: '3.8'
services:
  supabase_db:
    image: supabase/postgres:15.1.0.147
    container_name: ailocal_supabase_db
    restart: unless-stopped
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: localhost
    volumes:
    - ailocal_supabase_db:/var/lib/postgresql/data
    - ./supabase/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
    - ailocal_network
    command:
    - postgres
    - -c
    - config_file=/etc/postgresql/postgresql.conf
    - -c
    - log_statement=all
  supabase_kong:
    image: kong:2.8.1
    container_name: ailocal_supabase_kong
    restart: unless-stopped
    ports:
    - 8000:8000
    - 8443:8443
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-size-limiting,response-size-limiting,cors,key-auth,acl
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
    volumes:
    - ./supabase/kong.yml:/var/lib/kong/kong.yml:ro
    networks:
    - ailocal_network
    depends_on:
    - supabase_db
  supabase_auth:
    image: supabase/gotrue:v2.99.0
    container_name: ailocal_supabase_auth
    restart: unless-stopped
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: '9999'
      API_EXTERNAL_URL: http://localhost:8000
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgresql://supabase_auth_admin:postgres123@supabase_db:5432/postgres
      GOTRUE_SITE_URL: http://localhost:3000
      GOTRUE_URI_ALLOW_LIST: '*'
      GOTRUE_DISABLE_SIGNUP: 'false'
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: '3600'
      GOTRUE_JWT_SECRET: kdUtcO23wMrylbwBg224PcO_Pc_MoHlo7OmZ7N2-MMU
      GOTRUE_EXTERNAL_EMAIL_ENABLED: 'true'
      GOTRUE_MAILER_AUTOCONFIRM: 'false'
      GOTRUE_SMTP_ADMIN_EMAIL: admin@example.com
      GOTRUE_SMTP_HOST: supabase_inbucket
      GOTRUE_SMTP_PORT: '2500'
      GOTRUE_SMTP_USER: fake_mail_user
      GOTRUE_SMTP_PASS: fake_mail_password
      GOTRUE_SMTP_SENDER_NAME: fake_sender
      GOTRUE_MAILER_URLPATHS_INVITE: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_RECOVERY: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: /auth/v1/verify
    networks:
    - ailocal_network
    depends_on:
    - supabase_db
  supabase_rest:
    image: postgrest/postgrest:v11.2.0
    container_name: ailocal_supabase_rest
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgresql://authenticator:postgres123@supabase_db:5432/postgres
      PGRST_DB_SCHEMAS: public,storage,graphql_public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: kdUtcO23wMrylbwBg224PcO_Pc_MoHlo7OmZ7N2-MMU
      PGRST_DB_USE_LEGACY_GUCS: 'false'
      PGRST_APP_SETTINGS_JWT_SECRET: kdUtcO23wMrylbwBg224PcO_Pc_MoHlo7OmZ7N2-MMU
      PGRST_APP_SETTINGS_JWT_EXP: '3600'
    networks:
    - ailocal_network
    depends_on:
    - supabase_db
  supabase_realtime:
    image: supabase/realtime:v2.25.50
    container_name: ailocal_supabase_realtime
    restart: unless-stopped
    environment:
      PORT: '4000'
      DB_HOST: supabase_db
      DB_PORT: '5432'
      DB_USER: supabase_admin
      DB_PASSWORD: postgres123
      DB_NAME: postgres
      DB_AFTER_CONNECT_QUERY: SET search_path TO _realtime
      DB_ENC_KEY: supabaserealtime
      API_JWT_SECRET: kdUtcO23wMrylbwBg224PcO_Pc_MoHlo7OmZ7N2-MMU
      FLY_ALLOC_ID: fly123
      FLY_APP_NAME: realtime
      SECRET_KEY_BASE: kdUtcO23wMrylbwBg224PcO_Pc_MoHlo7OmZ7N2-MMU
      ERL_AFLAGS: -proto_dist inet_tcp
      ENABLE_TAILSCALE: 'false'
      DNS_NODES: ''''''
    networks:
    - ailocal_network
    depends_on:
    - supabase_db
  supabase_storage:
    image: supabase/storage-api:v0.40.4
    container_name: ailocal_supabase_storage
    restart: unless-stopped
    environment:
      ANON_KEY: i49aL1WjG_RF-gj37J8IabwdhqxxdrPdw1IwAVKB230
      SERVICE_KEY: BVcQmheTYDXSnzhwDB8p2674DzhFL4FzBcF8dMoa7JM
      POSTGREST_URL: http://supabase_rest:3000
      PGRST_JWT_SECRET: kdUtcO23wMrylbwBg224PcO_Pc_MoHlo7OmZ7N2-MMU
      DATABASE_URL: postgresql://supabase_storage_admin:postgres123@supabase_db:5432/postgres
      FILE_SIZE_LIMIT: '52428800'
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      REGION: stub
      GLOBAL_S3_BUCKET: stub
      ENABLE_IMAGE_TRANSFORMATION: 'true'
      IMGPROXY_URL: http://supabase_imgproxy:5001
    volumes:
    - ailocal_supabase_storage:/var/lib/storage
    networks:
    - ailocal_network
    depends_on:
    - supabase_db
    - supabase_rest
  n8n:
    image: n8nio/n8n:latest
    container_name: ailocal_n8n
    restart: unless-stopped
    ports:
    - 5678:5678
    environment:
      N8N_BASIC_AUTH_ACTIVE: 'true'
      N8N_BASIC_AUTH_USER: admin
      N8N_BASIC_AUTH_PASSWORD: admin123
      N8N_HOST: 0.0.0.0
      N8N_PORT: '5678'
      N8N_PROTOCOL: http
      WEBHOOK_URL: http://localhost:5678
      N8N_ENCRYPTION_KEY: dV6wnZeBc3Igxww1vN4OlfzRy75jqbm3yIGHFfxE81A
      EXECUTIONS_DATA_PRUNE: 'true'
      EXECUTIONS_DATA_MAX_AGE: '168'
      N8N_METRICS: 'true'
    volumes:
    - ailocal_n8n_data:/home/node/.n8n
    - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
    - ailocal_network
    depends_on:
    - supabase_db
  ollama:
    image: ollama/ollama:latest
    container_name: ailocal_ollama
    restart: unless-stopped
    ports:
    - 11434:11434
    volumes:
    - ailocal_ollama_data:/root/.ollama
    networks:
    - ailocal_network
    environment:
      OLLAMA_HOST: 0.0.0.0
      OLLAMA_ORIGINS: '*'
  redis:
    image: redis:7-alpine
    container_name: ailocal_redis
    restart: unless-stopped
    ports:
    - 6379:6379
    volumes:
    - ailocal_redis_data:/data
    networks:
    - ailocal_network
    command: redis-server --appendonly yes --requirepass redis123
  ailocal_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ailocal_app
    restart: unless-stopped
    ports:
    - 8080:8080
    environment:
      PYTHONPATH: /app
      OLLAMA_URL: http://ollama:11434
      SUPABASE_URL: http://supabase_kong:8000
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SUPABASE_SERVICE_KEY}
      N8N_URL: http://n8n:5678
      REDIS_URL: redis://redis123@redis:6379
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
    volumes:
    - ./rag_data:/app/rag_data
    - ./config:/app/config
    - ./logs:/app/logs
    networks:
    - ailocal_network
    depends_on:
    - supabase_db
    - supabase_kong
    - n8n
    - ollama
    - redis
volumes:
  ailocal_supabase_db: {}
  ailocal_supabase_storage: {}
  ailocal_n8n_data: {}
  ailocal_ollama_data: {}
  ailocal_redis_data: {}
networks:
  ailocal_network:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.0.0/16
